export const SET_ALERT = 'SET_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';

export const SET_TOAST = 'SET_TOAST';
export const CLEAR_TOAST = 'CLEAR_TOAST';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const ADD_ADMIN_HOTELS = 'ADD_ADMIN_HOTELS';
export const CLEAR_ADMIN_HOTELS = 'CLEAR_ADMIN_HOTELS';
export const LOADING_ADMIN_HOTELS = 'LOADING_ADMIN_HOTELS';
export const FETCH_ADMIN_HOTELS_ERROR = 'FETCH_ADMIN_HOTELS_ERROR';

export const ADD_HOTELS = 'ADD_HOTELS';
export const CLEAR_HOTELS = 'CLEAR_HOTELS';
export const LOADING_HOTELS = 'LOADING_HOTELS';
export const FETCH_HOTELS_ERROR = 'FETCH_HOTELS_ERROR';

export const ADD_HOTEL_DETAILS = 'ADD_HOTEL_DETAILS';
export const CLEAR_HOTEL_DETAILS = 'CLEAR_HOTEL_DETAILS';
export const LOADING_HOTEL_DETAILS = 'LOADING_HOTEL_DETAILS';
export const FETCH_HOTEL_DETAILS_ERROR = 'FETCH_HOTEL_DETAILS_ERROR';

export const ADD_BOOKINGS = 'ADD_BOOKINGS';
export const CLEAR_BOOKINGS = 'CLEAR_BOOKINGS';
export const LOADING_BOOKINGS = 'LOADING_BOOKINGS';
export const FETCH_BOOKINGS_ERROR = 'FETCH_BOOKINGS_ERROR';